=== likytho/Practica-2-SINT/iml.dtd
<!ELEMENT Interprete (Nombre, Nacionalidad, Album*)>
<!ELEMENT Nombre ((NombreC | NombreG), Id)>
<!ELEMENT NombreC (#PCDATA)>
<!ELEMENT NombreG (#PCDATA)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT Nacionalidad (#PCDATA)>
<!ELEMENT Album (NombreA, Año, Cancion+)>
<!ELEMENT NombreA (#PCDATA)>
<!ELEMENT Año (#PCDATA)>
<!ATTLIST Album tipo (nuevo|recopilatorio|mixto) #REQUIRED>
<!ATTLIST Album temas (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30) #IMPLIED>
<!ELEMENT Cancion (#PCDATA | NombreT | Duracion | Version)*>
<!ELEMENT NombreT (#PCDATA)>
<!ELEMENT Duracion (#PCDATA)>
<!ATTLIST Cancion estilo CDATA #REQUIRED>
<!ELEMENT Version (Nombre, IML)>
<!ELEMENT IML (#PCDATA)>

=== likytho/Practica-2-SINT/prueba1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Interprete SYSTEM "iml.dtd">
<Interprete>
	<Nombre>
		<NombreC>Juaquín</NombreC>
		<Id>0123456789</Id>
	</Nombre>
	<Nacionalidad>Español</Nacionalidad>
	<Album tipo="mixto" temas="1">
		<NombreA>Album sabina 1</NombreA>
		<Año>2002</Año>
		<Cancion estilo="gososo">
			<NombreT>Gosadera</NombreT>
			<Duracion>03:34</Duracion>
			<Version>
				<Nombre>
					<NombreC>Serrat</NombreC>
					<Id>9876543210</Id>
				</Nombre>
				<IML>serrat.xml</IML>
			</Version>
			<Version>
				<Nombre>
					<NombreG>Estopa</NombreG>
					<Id>0000000000</Id>
				</Nombre>
				<IML>estopa.xml</IML>
			</Version>
		</Cancion>	
	</Album>
</Interprete>

=== likytho/Practica-2-SINT/queen.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Interprete SYSTEM "http://clave.det.uvigo.es:8080/~sint153/p2/iml.dtd" >

<Interprete>
	<Nombre>
		<NombreG>The Queen</NombreG>
		<Id>TQEN</Id>
	</Nombre>

	<Nacionalidad>Italiano</Nacionalidad>

	<Album tipo="nuevo" temas="3">

		<NombreA>Sheeer Heart Attack</NombreA>
		<Año>1974</Año>

		<Cancion estilo="Heavy Metal">
			<NombreT>Father to son</NombreT>
			<Duración>03:51</Duración>
		</Cancion>
		
		<Cancion estilo="Heavy Metal">
			<NombreT>Nevermore</NombreT>
			<Duración>04:23</Duración>
				<Version>
					<Nombre>
						<NombreG>John Lennon</NombreG>
						<Id>JHNLNN</Id>
					</Nombre>
					<IML></IML>
				</Version>
		</Cancion>

		<Cancion estilo="Pop">
			<NombreT>Funny How Love Is</NombreT>
			<Duración>02:59</Duración>
				<Version>
					<Nombre>
						<NombreG>Joaquim Sabina</NombreG>
						<Id>JSAB</Id>
					</Nombre>
					<IML></IML>
				</Version>
		</Cancion>
	</Album>
</Interprete>

=== likytho/Practica-2-SINT/springsteen.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<!DOCTYPE Interprete SYSTEM "http://clave.det.uvigo.es:8080/~sint153/p2/iml.dtd" >

<Interprete>
 <Nombre>
  <NombreC>Bruce Springsteen</NombreC>
  <Id>sdfryghuie</Id>
 </Nombre>
 
 <Nacionalidad>Americano</Nacionalidad>
 
 <Album tipo="nuevo">
	<NombreA>Viva Springsteen, cojones</NombreA>
	
	<Año>2002</Año>
	
	<Cancion estilo="Rock">
	
	  <NombreT>Born to Run</NombreT>
	  Tema principal del disco
	  <Duracion>04:45</Duracion>
	  
	</Cancion>
	 
	<Cancion estilo="balada">
	  <NombreT>Una Canción Para La Magdalena</NombreT>
	  Sobre la Magdalena?
	  <Duracion>04:15</Duracion>
	  <Version>
	     <Nombre>
	       <NombreG>Juaquín</NombreG>
	       <Id>0123456789</Id>
	     </Nombre>
	    <IML>prueba1.xml</IML>
	  </Version>
	</Cancion>
	
	<Cancion estilo="rock">
	  Y alguno más
	  <NombreT>Cadillac Ranch</NombreT>
	  <Duracion>07:11</Duracion>
	</Cancion>
	
	<Cancion estilo="rock">
	  <NombreT>Dancing in the Dark</NombreT>
	  <Duracion>04:37</Duracion>
	  A Light in Darkness
	</Cancion>
 </Album>
 
 <Album tipo="recopilatorio" temas="4">
  <NombreA>Greatest Hits</NombreA>
  <Año>1995</Año>
  <Cancion estilo="Punk">
    <NombreT>Murder Incorporated</NombreT>
    <Duracion>05:02</Duracion>
  </Cancion>
   <Cancion estilo="Punk">
    <NombreT>Secret Garden</NombreT>
    <Duracion>04:37</Duracion>
  </Cancion>
  <Cancion estilo="pop">
    Ou yeah!
    <NombreT>Hungry Heart '95</NombreT>
    <Duracion>03:56</Duracion>
  </Cancion>
   <Cancion estilo="pop">
    <NombreT>The Ghost of Tom Joad</NombreT>
    <Duracion>04:57</Duracion>
    Que se mete en a cama a dormir
  </Cancion>
 </Album>
 
 <Album tipo="recopilatorio">
  <NombreA>Tracks</NombreA>
  <Año>1998</Año>
  <Cancion estilo="balada">
    <NombreT>Fastest man alive</NombreT>
    Al cielo
    <Duracion>04:07</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Eh, Flash</NombreT>
    Thanks
    <Duracion>03:40</Duracion>
  </Cancion>
  <Cancion estilo="balada">
    I found it!
    <NombreT>Hey, guys!</NombreT>
    <Duracion>04:27</Duracion>
  </Cancion>
   <Cancion estilo="pop">
    <NombreT>Juana la Loca</NombreT>
    <Duracion>05:35</Duracion>
    Te folla toda la boca
  </Cancion>
 </Album>
 
 <Album tipo="mixto" temas="4">
  <NombreA>Diario de un peaton</NombreA>
  <Año>2003</Año>
  <Cancion estilo="balada">
    <NombreT>La ciudad más hermosa del mundo</NombreT>
    <Duracion>04:56</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Marco</NombreT>
    Polo
    <Duracion>03:51</Duracion>
  </Cancion>
  <Cancion estilo="pop">
    A nosotros también
    <NombreT>Me encantan las mujeres</NombreT>
    <Duracion>04:30</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Cuando me hablan de dinero</NombreT>
    <Duracion>03:44</Duracion>
    Saco el maletín
  </Cancion>
 </Album>
 
 <Album tipo="nuevo">
  <NombreA>Nos sobran las putillas</NombreA>
  <Año>2000</Año>
  <Cancion estilo="balada">
    <NombreT>Que se come el yogurt</NombreT>
    Y seguirá comiéndoselo
    <Duracion>06:20</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Contigo me como el mundo</NombreT>
    Y sin ti no me como un rosco
    <Duracion>05:05</Duracion>
  </Cancion>
  <Cancion estilo="balada">
    Rajoy, le llamaban
    <NombreT>¿Quién me ha robado la nómina?</NombreT>
    <Duracion>06:54</Duracion>
  </Cancion>
   <Cancion estilo="pop">
    <NombreT>Conductores suicidas</NombreT>
    <Duracion>05:04</Duracion>
    Ese es Pires, sisi
  </Cancion>
 </Album>
 
</Interprete>

=== likytho/Practica-2-SINT/vivaldi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Interprete SYSTEM "iml.dtd">
<Interprete>
        <!--<Nombre>
                <NombreC>Vivaldi</NombreC>
                <Id>0000000010</Id>
        </Nombre>-->
        <Nacionalidad>Española</Nacionalidad>
        <Album tipo="recopilatorio" temas="1">
                <NombreA>Sinfonias vivaldi</NombreA>
                <Año>1000</Año>
                <Cancion estilo="jefe">
                        <NombreT>la crema</NombreT>
                        <Duracion>02:10</Duracion>
		</Cancion>
	</Album>
	<Album tipo="mixto" temas="1">
                <NombreA>Sinfonia 2</NombreA>
                <Año>1001</Año>
                <Cancion estilo="sin estilo">
                        <NombreT>tema 1</NombreT>
                        <Duracion>03:00</Duracion>
                </Cancion>
	</Album>	 
</Interprete>

=== likytho/Practica-2-SINT/serrat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Interprete SYSTEM "iml.dtd">
<Interprete>    
        <Nombre>
                <NombreC>Serrat</NombreC>
                <Id>9876543210</Id>
        </Nombre>
        <Nacionalidad>Italiano</Nacionalidad>
        <Album tipo="recopilatorio" temas="1">
                <NombreA>Album serrat 2</NombreA>
                <Año>2000</Año>
                <Cancion estilo="acosador">
                        <NombreT>Remix sabina</NombreT>
                        <Duracion>03:00</Duracion>
                        <Version>
                                <Nombre>
                                        <NombreG>Estopa</NombreG>
                                        <Id>0000000000</Id>
                                </Nombre>
                                <IML>estopa.xml</IML>
                        </Version>
                        <Version>
                                <Nombre>
                                        <NombreC>Vivaldi</NombreC>
                                        <Id>0000000010</Id>
                                </Nombre>
                                <IML>vivaldi.xml</IML>
                        </Version>
                </Cancion>
        </Album>
</Interprete>

=== likytho/Practica-2-SINT/estopa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Interprete SYSTEM "iml.dtd">
<Interprete>
        <Nombre>
                <NombreG>Estopa</NombreG>
                <Id>0000000000</Id>
        </Nombre>
        <Nacionalidad>Española</Nacionalidad>
        <Album tipo="recopilatorio" temas="1">
                <NombreA>Album estopa 1</NombreA>
                <Año>2001</Año>
                <Cancion estilo="sin">
			Esto funciona bien
                        <NombreT>Repartiendo</NombreT>
                        <Duracion>02:10</Duracion>
		</Cancion>
	</Album>
	<Album tipo="mixto" temas="1">
                <NombreA>Album éstopa 2</NombreA>
                <Año>2002</Año>
                <Cancion estilo="gososo">
			esto
                        <NombreT>estopiña</NombreT>
			es
                        <Duracion>03:00</Duracion>
			una buena
                        <Version>
                                <Nombre>
                                        <NombreC>Serrat</NombreC>
                                        <Id>9876543210</Id>
                                </Nombre>
                                <IML>serrat.xml</IML>
                        </Version>
			cancion
                </Cancion>
        </Album>
</Interprete>

=== likytho/Practica-2-SINT/sabina.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>

<!DOCTYPE Interprete SYSTEM "p2/iml.dtd" >

<Interprete>
 <Nombre>
  <NombreC>Joaquin Sabina</NombreC>
  <Id>sdfryghuia</Id>
 </Nombre>
 
 <Nacionalidad>español</Nacionalidad>
 
 <Album tipo="nuevo">
	<NombreA>19 días y 500 noches</NombreA>
	
	<Año>2002</Año>
	
	<Cancion estilo="pop">
	
	  <NombreT>19 días y 500 noches</NombreT>
	  Tema principal del disco
	  <Duracion>04:45</Duracion>
	  
	</Cancion>
	 
	<Cancion estilo="balada">
	  <NombreT>Una Canción Para La Magdalena</NombreT>
	  Sobre la Magdalena?
	  <Duracion>04:15</Duracion>
	  <Version>
	     <Nombre>
	       <NombreG>Bruce Springsteen</NombreG>
	       <Id>sdfryghuie</Id>
	     </Nombre>
	    <IML>springsteen.xml</IML>
	  </Version>
	</Cancion>
	
	<Cancion estilo="rock">
	  Y alguno más
	  <NombreT>A Mis Cuarenta y Diez</NombreT>
	  <Duracion>07:11</Duracion>
	</Cancion>
	
	<Cancion estilo="rock">
	  <NombreT>Cerrado Por Derribo</NombreT>
	  <Duracion>04:37</Duracion>
	  Para siempre
	</Cancion>
 </Album>
 
 <Album tipo="nuevo" temas="5">
  <NombreA>Física y Química</NombreA>
  <Año>2001</Año>
  <Cancion estilo="balada">
    <NombreT>Y nos dieron las diez</NombreT>
    Y las once
    <Duracion>05:02</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>La del pirata cojo</NombreT>
    Con pata de palo
    <Duracion>04:37</Duracion>
  </Cancion>
  <Cancion estilo="balada">
    Esta es
    <NombreT>La canción de las noches perdidas</NombreT>
    <Duracion>03:56</Duracion>
  </Cancion>
   <Cancion estilo="balada">
    <NombreT>Peor para el sol</NombreT>
    <Duracion>04:57</Duracion>
    Que se mete en a cama a dormir
  </Cancion>
   <Cancion estilo="pop">
    <NombreT>Pastillas para no soñar</NombreT>
    <Duracion>03:55</Duracion>
    No hay
   </Cancion>
 </Album>
 
 <Album tipo="recopilatorio">
  <NombreA>Todos hablan de ti</NombreA>
  <Año>2004</Año>
  <Cancion estilo="balada">
    <NombreT>Pongamos que hablo de Madrid</NombreT>
    Al cielo
    <Duracion>04:07</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Eh, Sabina</NombreT>
    Tú sí que sabes
    <Duracion>03:40</Duracion>
  </Cancion>
  <Cancion estilo="balada">
    Quiero mudarme hace años
    <NombreT>Calle Melancolía</NombreT>
    <Duracion>04:27</Duracion>
  </Cancion>
   <Cancion estilo="pop">
    <NombreT>Juana la Loca</NombreT>
    <Duracion>05:35</Duracion>
    Y Felipe el Hermoso
  </Cancion>
 </Album>
 
 <Album tipo="mixto" temas="4">
  <NombreA>Diario de un peaton</NombreA>
  <Año>2003</Año>
  <Cancion estilo="balada">
    <NombreT>La canción más hermosa del mundo</NombreT>
    Con Pablo Milanés
    <Duracion>04:56</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Doble vida</NombreT>
    Y triple a veces
    <Duracion>03:51</Duracion>
  </Cancion>
  <Cancion estilo="pop">
    Nosotros también
    <NombreT>Semos diferentes</NombreT>
    <Duracion>04:30</Duracion>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Cuando me hablan del destino</NombreT>
    <Duracion>03:44</Duracion>
    Me pongo furioso
  </Cancion>
 </Album>
 
 <Album tipo="nuevo">
  <NombreA>Nos sobran los motivos</NombreA>
  <Año>2000</Año>
  <Cancion estilo="balada">
    <NombreT>Que se llama Soledad</NombreT>
    Y seguirá llamándose
    <Duracion>06:20</Duracion>
    <Version>
      <Nombre>
         <NombreG>Siniestro Total</NombreG>
         <Id>sdfryghuii</Id>
      </Nombre>
      <IML>siniestro.xml</IML>
    </Version>
  </Cancion>
   <Cancion estilo="rock">
    <NombreT>Contigo</NombreT>
    Y sin ti
    <Duracion>05:05</Duracion>
  </Cancion>
  <Cancion estilo="balada">
    Así estoy yo sin ti
    <NombreT>¿Quién me ha robado el mes de abril?</NombreT>
    <Duracion>06:54</Duracion>
  </Cancion>
   <Cancion estilo="pop">
    <NombreT>Conductores suicidas</NombreT>
    <Duracion>05:04</Duracion>
    Todos somos un poco así
  </Cancion>
 </Album>
 
</Interprete>
